# Generated by Django 2.2.4 on 2019-12-21 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souvenir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile',
        ),
    ]
